name: Deploy to production environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: set output
        run: echo version=$(grep -Po 'version=\K.*' gradle.properties) >> $GITHUB_OUTPUT
        id: get-version

      - name: Teste
        run: echo $version
